### ISSUE TITLE
Acquire SSDs to make writing to disk faster

### ISSUE THREAD

**Issue by iReynaldo** [UConnBGP/IssueBoard#15]

**Comment by c-morris** [comment]
Justin is going to test how long the 256-table join takes and then make the case to Prof Herzberg that buying SSDs will be faster and more efficient than swapping chunks of extrapolation results in and out of RAM. 

The 256-table join is expected to take an impossibly long time to terminate.

**Comment by c-morris** [comment]
Update: Waldy and Ldm will be installing a 600 GB 10K SAS drive most likely this afternoon (2019-04-08). 

Xinyu's timing test on his own SSD was convincing enough that we are eventually going to purchase some SSDs for the server, but this will take some unknown amount of time.
