### ISSUE TITLE
Extrapolator ignores Max Length of ROAs

### ISSUE THREAD

**Issue by c-morris** [UConnBGP/IssueBoard#2]
There is a bug in the Extrapolator where it ignores the max length attribute of ROAs. 

To fix this, Justin is going to make the MRT announcements table *only* save prefixes which are covered by a ROA. That way the Extrapolator does not need to do any filtering using the roas table since it will already be done beforehand.

**Comment by c-morris** [comment]
Normal brain: fix the bug by selecting announcements with prefixes equal to or contained within the max length of the ROA.

Galaxy brain: fix the bug by ignoring ROAs.

But actually,  the extrapolator is meant to be a reusable, standalone component in this project. It should not require a "roas" table to function and it should not filter its input based on those ROAs.

**Comment by iReynaldo** [comment]
Ignorant and Practical Brain: Correct, the extrapolator should not require a ROAs table, but lets leave it like that for now.
