### ISSUE TITLE
Include policy descriptions in API

### ISSUE THREAD

**Issue by c-morris** [UConnBGP/IssueBoard#23]
The API that returns the asn_hijack_stats should also include a brief description of the policy that can be used as a more-helpful tooltip over the question mark icon in the table.

**Comment by c-morris** [comment]
The tooltip should go here
![tooltip](https://user-images.githubusercontent.com/8572969/55693086-19c98f00-597b-11e9-83bb-05445b2a153f.png)

**Comment by iReynaldo** [comment]
Currently added in https://github.com/UConnBGP/ForecastAPI

Will be added in lib_bgp_data after permission granted.
