### ISSUE TITLE
Add Subscription Feature

### ISSUE THREAD

**Issue by iReynaldo** [UConnBGP/IssueBoard#39]
Add a Subscribe feature to the Website so visitors can subscribe to get updates on project progress.

I suggest that we do this the easiest way possible.
We can leverage existing platforms that can do this:
* Twitter
* Facebook
* A free [MailChimp](https://mailchimp.com) solution

Open to other ideas.
**The solution also needs to support methods for subscribers to request updates on things. Like "What's up with that API yo?"**

**Comment by c-morris** [comment]
James did this with a gravity form. It's live here [https://sidr.engr.uconn.edu/](https://sidr.engr.uconn.edu/)

![subscribe_by_email](https://user-images.githubusercontent.com/8572969/57885691-8137f180-77f9-11e9-9930-54d29317486a.png)
