### ISSUE TITLE
read about AS sets and figure out what to do with that

### ISSUE THREAD

**Issue by c-morris** [UConnBGP/IssueBoard#47]
AS Sets introduce ambiguity into the AS_PATH of a BGP announcement. They are described in the BGP-4 RFC and this best-practices RFC also explains why they are not good for security in interdomain routing. 

BGP 4: https://tools.ietf.org/html/rfc4271

Recommendation for not using AS_SET: https://tools.ietf.org/html/rfc6472

**Comment by Iuconnu** [comment]
Decision was made to ignore AS Sets.
